version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gebmoll_app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: gebmoll_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: gebmoll_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gebmoll
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gebmoll_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_MYSQL_SSL: false
    depends_on:
      - db
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
